apiVersion: v1
kind: PersistentVolume
metadata:
  name: devproject-mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: devproject-storage
  hostPath:
    path: /data/devproject-mongo
